# Generated by Django 6.0.7 on 2026-08-30 08:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_studentprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                default="UTC",
                max_length=64,
                validators=[accounts.models.validate_timezone],
            ),
        ),
    ]
