# Generated by Django 6.0.7 on 2026-08-20 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
        ("portfolio", "0004_teacherprofile_trial_duration_minutes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "confirmed"])),
                fields=("teacher", "date", "start_time"),
                name="unique_active_teacher_datetime_booking",
            ),
        ),
    ]
