# Generated by Django 6.0.7 on 2026-08-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_booking_unique_active_teacher_datetime_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancellation_requested",
            field=models.BooleanField(default=False),
        ),
    ]
