# Generated by Django 6.0.7 on 2026-08-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_booking_cancellation_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="completion_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
