# Generated by Django 6.0.7 on 2026-08-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
