# Generated by Django 6.0.7 on 2026-08-31 07:15

from django.db import migrations


def clear_bookings(apps, schema_editor):
    Booking = apps.get_model('booking', 'Booking')
    Booking.objects.all().delete()

    
class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_booking_completion_note"),
    ]

    operations = [
        migrations.RunPython(clear_bookings, migrations.RunPython.noop),
    ]
