# Generated by Django 6.0.7 on 2026-08-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_review_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
