# Generated by Django 6.0.7 on 2026-08-31 07:01

import datetime
from django.db import migrations, models

def clear_bookings(apps, schema_editor):
    Booking = apps.get_model('booking', 'Booking')
    Booking.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0005_clear_test_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="start_time",
        ),
        migrations.AddField(
            model_name="booking",
            name="end_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 8, 31, 6, 57, 13, 116314, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="start_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 8, 31, 7, 1, 1, 512039, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
