# Generated by Django 6.0.7 on 2026-09-07 07:21

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_remove_booking_date_remove_booking_end_time_and_more"),
        ("portfolio", "0008_alter_certificate_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_active_teacher_datetime_booking",
        ),
        migrations.AlterField(
            model_name="booking",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "confirmed"])),
                fields=("teacher", "start_at"),
                name="unique_active_teacher_datetime_booking",
            ),
        ),
    ]
