# Generated by Django 6.0.7 on 2026-09-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "booking",
            "0007_remove_booking_unique_active_teacher_datetime_booking_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("disputing", "Disputing"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
