# Generated by Django 6.0.7 on 2026-09-20 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0008_alter_booking_status"),
        ("portfolio", "0010_teacherprofile_meeting_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reminder_1h_sent",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="reminder_24h_sent",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "start_at"], name="booking_boo_status_bcac9d_idx"
            ),
        ),
    ]
