# Generated by Django 6.0.7 on 2026-09-21 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0009_booking_reminder_1h_sent_booking_reminder_24h_sent_and_more"),
        ("portfolio", "0010_teacherprofile_meeting_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherDailyDigestRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        help_text="The date of the schedule summarized in this digest (in teacher's timezone)."
                    ),
                ),
                ("booking_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("skipped_empty", "Skipped Empty")],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_digest_records",
                        to="portfolio.teacherprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-target_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("teacher", "target_date"),
                        name="unique_teacher_daily_digest_target_date",
                    )
                ],
            },
        ),
    ]
