# Generated by Django 6.0.7 on 2026-10-04 06:20

import django.core.validators
from django.db import migrations, models


def backfill_booking_duration_minutes(apps, schema_editor):
    Booking = apps.get_model("booking", "Booking")
    for booking in Booking.objects.all():
        if booking.start_at and booking.end_at:
            delta_seconds = (booking.end_at - booking.start_at).total_seconds()
            delta_minutes = int(round(delta_seconds / 60))
            if delta_minutes > 0:
                booking.duration_minutes = delta_minutes
            elif booking.lesson_type == "trial":
                booking.duration_minutes = 25
            else:
                booking.duration_minutes = 50
        elif booking.lesson_type == "trial":
            booking.duration_minutes = 25
        else:
            booking.duration_minutes = 50
        booking.save(update_fields=["duration_minutes"])


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0010_teacherdailydigestrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(
                default=50, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.RunPython(
            backfill_booking_duration_minutes,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
