# Generated by Django 6.0.7 on 2026-08-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="lesson_duration_minutes",
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
