# Generated by Django 6.0.7 on 2026-08-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_teacherprofile_lesson_duration_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="headline",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
