# Generated by Django 6.0.7 on 2026-08-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_teacherprofile_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="trial_duration_minutes",
            field=models.PositiveSmallIntegerField(default=25),
        ),
    ]
