# Generated by Django 6.0.7 on 2026-08-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_teacherprofile_trial_duration_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
