# Generated by Django 6.0.7 on 2026-09-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_teacherprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="instant_tutoring_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Allow students to book same-day lessons (subject to a 1-hour buffer).",
            ),
        ),
    ]
