# Generated by Django 6.0.7 on 2026-09-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_teacherprofile_instant_tutoring_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="instagram_username",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="telegram_username",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="whatsapp_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
