# Generated by Django 6.0.7 on 2026-09-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0008_alter_certificate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="hero_image",
            field=models.ImageField(blank=True, null=True, upload_to="hero_images/"),
        ),
    ]
