# Generated by Django 6.0.7 on 2026-09-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_teacherprofile_hero_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="meeting_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Your permanent video meeting link (e.g. Google Meet or Zoom) included in lesson confirmation and reminder emails.",
                max_length=500,
            ),
        ),
    ]
