# Generated by Django 6.0.7 on 2026-10-03 14:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0010_teacherprofile_meeting_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="lesson_price_25",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
